language: ruby
cache: bundler
sudo: required
dist: trusty

rvm:
  - 2.4.2

addons:
  chrome: stable
script:
  - bundle exec jekyll build
  - bundle exec rspec
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
