language: ruby
rvm:
  - 2.4.2
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html --allow_hash_href --alt-ignore '/.*/'
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
