dist: trusty
sudo: required
language: ruby
rvm:
  - 2.4
addons:
  apt:
    packages:
      - google-chrome-stable
script:
  - bundle exec jekyll build
  - bundle exec rake wax:test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
