language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
sudo: required
addons:
  chrome: stable
script:
  - bundle exec jekyll build
  - bundle exec rake wax:test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
