# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Sudan Historical Photography Archive
  ar: ارشيف الصور التاريخي السوداني
email: sudanphoto@uofk.edu
description:
  en: A digital archive of photography of Sudan, run by the history department of Khartoum University.
  ar: ارشيف الصور التاريخي في قسم التاريخ جامعة الخرطوم
index:
  en: index.html
  ar: home2.html
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
